version: '2.24'

services:

  fresh_produce_api:
    container_name: fresh_produce_api
    restart: always
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
